import type { CustomerAccount, QueueStat, TaskItem, TriageItem } from "@/lib/types"

export const queueStats: QueueStat[] = [
  { label: "Total Outstanding", value: "₹24.6L", detail: "↑12% vs last month" },
  { label: "Active Defaulters", value: "142", detail: "18 accounts in 60+ bucket" },
  { label: "Reminders Sent Today", value: "67", detail: "Target: first send in <60s" },
  { label: "Avg Days Overdue", value: "41 days", detail: "9 newly flagged this week" },
]

export const customerAccounts: CustomerAccount[] = [
  {
    id: "cust-ramesh",
    customerName: "Ramesh Patil",
    accountRef: "Self-pay #IP2024081",
    payerType: "Self-pay",
    agingDays: 63,
    bucket: "60+ days",
    outstanding: 48200,
    riskLevel: "High Risk",
    modifierType: "penalty",
    modifierLabel: "+12% penalty",
    modifierValue: "+12% penalty if unpaid this week",
    reminderCount: 4,
    lastAction: "Reminder sent 2h ago",
    lastChannel: "Email",
    responseHistory: ["Opened email, no reply", "Call disconnected"],
    aiPriorityScore: 98,
    aiSummary: "Long aging, high balance, and no commitment in the last 7 days.",
    draftMessage:
      "Hello Ramesh Patil, your outstanding balance of ₹48,200 for Self-pay #IP2024081 is now 63 days overdue. A +12% penalty applies if the dues remain unpaid this week. Please confirm your payment plan today so we can help you avoid further escalation.",
  },
  {
    id: "cust-sunita",
    customerName: "Sunita Medicare",
    accountRef: "Insurance #INS2024092",
    payerType: "Insurance",
    agingDays: 51,
    bucket: "45-day bucket",
    outstanding: 124000,
    riskLevel: "Watch",
    modifierType: "penalty",
    modifierLabel: "+8% penalty",
    modifierValue: "+8% penalty if unpaid this cycle",
    reminderCount: 2,
    lastAction: "Follow-up due today",
    lastChannel: "Email",
    responseHistory: ["Requested statement copy"],
    aiPriorityScore: 92,
    aiSummary: "Large balance and prior engagement suggest a strong follow-up opportunity.",
    draftMessage:
      "Hello Sunita Medicare team, this is a reminder that ₹1,24,000 linked to Insurance #INS2024092 is 51 days overdue. A +8% penalty applies if payment is delayed further. Please share your expected clearance date or any issue blocking payment.",
  },
  {
    id: "cust-priya",
    customerName: "Priya Sharma",
    accountRef: "Self-pay #OP2024103",
    payerType: "Self-pay",
    agingDays: 32,
    bucket: "30-day bucket",
    outstanding: 18750,
    riskLevel: "Normal",
    modifierType: "incentive",
    modifierLabel: "−5% incentive",
    modifierValue: "−5% incentive if paid today",
    reminderCount: 1,
    lastAction: "Newly added yesterday",
    lastChannel: "WhatsApp",
    responseHistory: ["Invoice delivered"],
    aiPriorityScore: 76,
    aiSummary: "Recently overdue with good response history, so a softer nudge is appropriate.",
    draftMessage:
      "Hello Priya Sharma, your payment of ₹18,750 for Self-pay #OP2024103 is now 32 days overdue. We can apply a −5% incentive if you complete payment today. Reply here if you need a fresh invoice copy or support with the payment process.",
  },
  {
    id: "cust-meera",
    customerName: "Meera Diagnostics",
    accountRef: "Corporate #CORP2024116",
    payerType: "Corporate",
    agingDays: 67,
    bucket: "60+ days",
    outstanding: 96500,
    riskLevel: "High Risk",
    modifierType: "penalty",
    modifierLabel: "+12% penalty",
    modifierValue: "+12% penalty now active",
    reminderCount: 5,
    lastAction: "No response after final email",
    lastChannel: "Email",
    responseHistory: ["Bounce resolved", "No reply after resend"],
    aiPriorityScore: 96,
    aiSummary: "Repeated no-response behavior makes this account a same-day action item.",
    draftMessage:
      "Hello Meera Diagnostics, ₹96,500 for Corporate #CORP2024116 remains overdue by 67 days and now carries a +12% penalty. Please confirm payment today or let us know if there is a dispute requiring review.",
  },
  {
    id: "cust-ashok",
    customerName: "Ashok Enterprises",
    accountRef: "Distributor #DIST2024122",
    payerType: "Distributor",
    agingDays: 44,
    bucket: "30-day bucket",
    outstanding: 55800,
    riskLevel: "Watch",
    modifierType: "penalty",
    modifierLabel: "+8% penalty",
    modifierValue: "+8% penalty from day 45",
    reminderCount: 2,
    lastAction: "Reply received this morning",
    lastChannel: "SMS",
    responseHistory: ["Asked for 7-day extension"],
    aiPriorityScore: 84,
    aiSummary: "Engaged customer nearing escalation threshold; confirm the promised date.",
    draftMessage:
      "Hello Ashok Enterprises, your outstanding payment of ₹55,800 for Distributor #DIST2024122 is 44 days overdue. A +8% penalty begins from day 45. Please confirm whether payment will be completed within the next 24 hours.",
  },
]

export const triageFeed: TriageItem[] = [
  {
    id: "triage-1",
    customerId: "cust-sunita",
    customerName: "Sunita Medicare",
    receivedAt: "11:20 AM",
    rawReply: "Please hold collection action until we reconcile the insurer short-payment line items.",
    classification: "Disputed — task created",
    actionTaken: "Task created for Billing / Dispute Handler",
    followUp: "Awaiting dispute review",
  },
  {
    id: "triage-2",
    customerId: "cust-ashok",
    customerName: "Ashok Enterprises",
    receivedAt: "10:05 AM",
    rawReply: "We will clear the amount by Monday once the PO release is complete.",
    classification: "Payment commitment",
    actionTaken: "Follow-up auto-set for 48h",
    followUp: "Commitment logged",
  },
  {
    id: "triage-3",
    customerId: "cust-meera",
    customerName: "Meera Diagnostics",
    receivedAt: "Yesterday",
    rawReply: "No reply received after three reminders.",
    classification: "No response — flag updated",
    actionTaken: "Risk level updated to High Risk",
    followUp: "Escalation suggested",
  },
]

export const tasks: TaskItem[] = [
  {
    id: "task-1",
    customerId: "cust-sunita",
    customerName: "Sunita Medicare",
    taskType: "Resolve insurer deduction dispute",
    status: "Open",
    createdAt: "Today, 11:21 AM",
    assignedTo: "Anita Rao",
    notes: "Validate the insurer short-payment line items and share reconciliation back to collections.",
    auditTrail: [
      "AI triage marked as dispute",
      "Task auto-created from customer reply",
      "Manager review pending",
    ],
  },
  {
    id: "task-2",
    customerId: "cust-ramesh",
    customerName: "Ramesh Patil",
    taskType: "Manager escalation for repeated non-response",
    status: "In Progress",
    createdAt: "Yesterday, 4:10 PM",
    assignedTo: "Vikram Shah",
    notes: "High Risk account with no commitment despite four touches. Evaluate final escalation wording.",
    auditTrail: [
      "Flag upgraded to High Risk",
      "Escalation assigned to Finance Manager",
      "Callback planned for today afternoon",
    ],
  },
  {
    id: "task-3",
    customerId: "cust-priya",
    customerName: "Priya Sharma",
    taskType: "Confirm partial payment receipt",
    status: "Closed",
    createdAt: "Apr 1, 2:40 PM",
    assignedTo: "Neha Joshi",
    notes: "Customer requested revised receipt after partial settlement.",
    auditTrail: [
      "Partial payment marked in system",
      "Receipt re-issued",
      "Closed with outcome: Partial",
    ],
  },
]
